# Numpy Kütüphanesi

In [1]:
import numpy as np

In [2]:
my_list = [10,20,30,40]

In [3]:
type(my_list)

list

In [4]:
np.array(my_list)

array([10, 20, 30, 40])

In [5]:
my_np_array = np.array([10,20,30,40])

In [6]:
type(my_np_array)

numpy.ndarray

In [7]:
my_np_array.max()

40

In [8]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [9]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [10]:
np.random.random(5)

array([0.83106064, 0.32501458, 0.36524244, 0.65114244, 0.35271505])

# Aritmetik İşlemler

In [11]:
array1 = [1, 2]
array2 = [2, 3]

In [12]:
array1 + array2 

[1, 2, 2, 3]

In [13]:
numpy_array1 = np.array(array1)
numpy_array2 = np.array(array2)

In [14]:
numpy_array1 + numpy_array2

array([3, 5])

In [15]:
numpy_array1 - numpy_array2

array([-1, -1])

In [16]:
numpy_array1 * numpy_array2

array([2, 6])

In [17]:
other_array = np.array([10, 20, 30, 40, 50])

In [18]:
other_array.min()

10

In [19]:
other_array.max()

50

In [20]:
other_array.sum()

150

# Index Mantığı

In [21]:
np_array = np.arange(0, 10)

In [22]:
np_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np_array[0]

0

In [24]:
np_array[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [25]:
np_array[2:6:2]

array([2, 4])

In [26]:
np.random.randn(4)

array([-0.16582242, -0.29484264, -1.00029532, -2.91783153])

In [27]:
np.random.randn(4,4)

array([[ 0.3114407 ,  1.18539614, -1.39725847,  0.69381621],
       [-0.49389025, -1.34836209, -0.37096432, -0.18633504],
       [ 0.3555408 , -0.17442852,  0.41406532,  0.08440567],
       [ 1.38348776,  0.80017848, -0.00274207,  2.10254261]])

In [28]:
np.random.randint(1, 300, 5)

array([125,  77, 243, 273, 226])

# Numpy Matrisleri

In [34]:
my_matrix = [[5,10], [15,20]]

In [35]:
my_matrix[0]

[5, 10]

In [36]:
my_matrix[1][0]

15

In [37]:
# my_matrix.sum()

Burası hata verecektir çünkü listelerin böyle bir özelliği yok.

In [38]:
numpy_matrix = np.array([[5,10], [15,20]])

In [39]:
numpy_matrix

array([[ 5, 10],
       [15, 20]])

In [40]:
numpy_matrix.sum()

50

In [42]:
np.ones(4)

array([1., 1., 1., 1.])

In [43]:
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [44]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [45]:
np.random.random((3,3))

array([[0.16910463, 0.27501174, 0.76343182],
       [0.66242659, 0.14235175, 0.13536631],
       [0.30568883, 0.86370659, 0.92252849]])

# Matrixlerde Aritmetik İşlemler

In [52]:
first_array = np.array([[10,20], [30,40]])
first_array.shape

(2, 2)

In [53]:
second_array = np.array([[5,15], [25,35]])
second_array.shape

(2, 2)

In [54]:
first_array + second_array

array([[15, 35],
       [55, 75]])

In [55]:
first_array * 10

array([[100, 200],
       [300, 400]])

In [56]:
first_array / 10

array([[1., 2.],
       [3., 4.]])

In [57]:
third_array = np.array([[10], [20]])
third_array.shape

(2, 1)

In [59]:
first_array, third_array

(array([[10, 20],
        [30, 40]]),
 array([[10],
        [20]]))

In [60]:
first_array + third_array

array([[20, 30],
       [50, 60]])

# Matrix Çarpımı

In [61]:
first_matrix = np.array([[10,20,30]])

In [62]:
first_matrix

array([[10, 20, 30]])

In [63]:
second_matrix = np.array([[2,3], [2,3], [2,3]])

In [64]:
second_matrix

array([[2, 3],
       [2, 3],
       [2, 3]])

In [67]:
result_matrix = first_matrix.dot(second_matrix) 

In [68]:
result_matrix

array([[120, 180]])

# Önemli Numpy Özellikleri

In [69]:
new_array = np.random.randint(1, 100, 20)
new_array

array([81, 50, 13, 39, 52, 81, 14, 31, 57,  2, 37, 60, 22, 95, 37, 11, 54,
       54, 34, 52])

In [70]:
new_array > 25

array([ True,  True, False,  True,  True,  True, False,  True,  True,
       False,  True,  True, False,  True,  True, False,  True,  True,
        True,  True])

In [71]:
new_array[new_array > 25]

array([81, 50, 39, 52, 81, 31, 57, 37, 60, 95, 37, 54, 54, 34, 52])

In [72]:
matrix_array = np.array([[10,20], [20,30], [30,40]])
matrix_array

array([[10, 20],
       [20, 30],
       [30, 40]])

In [73]:
matrix_array.transpose()

array([[10, 20, 30],
       [20, 30, 40]])

In [74]:
matrix_array.T

array([[10, 20, 30],
       [20, 30, 40]])

In [77]:
matrix_array.reshape(2,3)

array([[10, 20, 20],
       [30, 30, 40]])

In [78]:
data = np.array([10, 12, 13, 15, 18, 25, 100, 105])

In [79]:
data.mean()

37.25

In [80]:
data.std()

37.9333296719389

In [82]:
z_scores = (data - data.mean()) / data.std()

In [84]:
outliers = data[np.abs(z_scores > 1)]
outliers

array([100, 105])

2x + 3y = 8 and 5x + 7y = 19

In [86]:
# coefficents
A = np.array([[2,3], [5,7]])

# constants
b = np.array([8, 19])

In [88]:
solution = np.linalg.solve(A, b)

In [89]:
solution

array([1., 2.])