In [1]:
import torch

In [2]:
torch.cuda.is_available()

True

In [3]:
torch.backends.mps.is_available()

False

Bu MAC kullananlar içindir.

In [4]:
device = "cuda" if torch.cuda.is_available() else "cpu"

In [5]:
device

'cuda'

In [6]:
tensor = torch.tensor([1,2,3])

In [7]:
tensor

tensor([1, 2, 3])

In [8]:
tensor.device

device(type='cpu')

Bunu GPU yapmanın 3 yolu var.

### 1- Manuel

In [9]:
tensor_on_gpu = tensor.to(device)

In [10]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [11]:
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

Numpy'a çevirirken hata çıkar.

In [12]:
tensor_numpy = tensor_on_gpu.cpu().numpy()

In [13]:
tensor_numpy

array([1, 2, 3], dtype=int64)

### 2- Context Manager

In [14]:
with torch.device(device):
    tensor2 = torch.tensor([1,2,3])
    layer = torch.nn.Linear(20,30)

In [15]:
tensor2

tensor([1, 2, 3], device='cuda:0')

In [17]:
layer.weight.device

device(type='cuda', index=0)

### 3- Set Default Device

In [19]:
torch.set_default_device(device)

In [20]:
tensor3 = torch.tensor([1,2,3])
layer2 = torch.nn.Linear(20,30)

In [21]:
tensor3.device

device(type='cuda', index=0)

In [22]:
layer2.weight.device

device(type='cuda', index=0)

In [23]:
torch.set_default_device("cpu")

In [24]:
tensor3.device

device(type='cuda', index=0)