In [2]:
#!pip install torch torchvision

In [3]:
import torch
import numpy as np

In [4]:
torch.tensor(10)

tensor(10)

In [5]:
torch.tensor([10, 20])

tensor([10, 20])

In [6]:
x = torch.tensor(10)
type(x)

torch.Tensor

In [7]:
x + 10

tensor(20)

In [8]:
x - 20

tensor(-10)

In [9]:
x / 20

tensor(0.5000)

PyTorch'da her şey tensor olarak geçer. Scalar, vektör veya matrix diye ayrım yapılmaz.

In [11]:
x.dim()

0

In [12]:
x.shape

torch.Size([])

In [13]:
x.item()

10

In [14]:
numpy_int = np.int32(20)
numpy_int

20

In [15]:
numpy_int + 10

30

In [16]:
numpy_int - 20

0

In [17]:
type(numpy_int)

numpy.int32

In [18]:
scalar_from_np = torch.tensor(numpy_int)

In [19]:
scalar_from_np

tensor(20, dtype=torch.int32)

Numpy ve Torch.tensor benzer mantık ile çalışır. Ayrıca torch tensorların default tipini int32 olarak alır.

In [20]:
new_scalar = torch.tensor(25, dtype = torch.int32)
new_scalar

tensor(25, dtype=torch.int32)

In [23]:
tensor_float = torch.tensor(3.14)
tensor_float.dtype

torch.float32

In [24]:
tensor_float_64 = torch.tensor(3.14, dtype = torch.float64)
tensor_float_64

tensor(3.1400, dtype=torch.float64)

In [25]:
vector = torch.tensor([1,2,3])

In [26]:
vector.ndim

1

In [27]:
vector.shape

torch.Size([3])

- `[` sayısı dimension sayısını verir
- eleman sayısı shape verir

In [28]:
matrix = torch.tensor([[1,2], [3,4]])

In [29]:
matrix.dim()     # or matrix.ndim

2

In [30]:
matrix.shape

torch.Size([2, 2])

In [39]:
tensor_example = torch.tensor([[[1,2,3] , [4,5,6], [7,8,9]]])

In [40]:
tensor_example

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [41]:
tensor_example.ndim

3

In [42]:
tensor_example.shape

torch.Size([1, 3, 3])

Bunun anlamı 3 x 3'de 1 boyut var demektir.

In [43]:
float_32_tensor = torch.tensor(
    data = [3.0, 6.0, 9.0],
    dtype = None, # default değeri alır
    device = None, # cpu or gpu
    requires_grad = False # öğrensin mi öğrenmesin mi
)

In [44]:
float_32_tensor

tensor([3., 6., 9.])

In [45]:
float_32_tensor.dim()

1

In [46]:
float_32_tensor.shape

torch.Size([3])

In [47]:
float_32_tensor.dtype

torch.float32

In [48]:
float_32_tensor.device

device(type='cpu')