In [1]:
import torch
import numpy as np

In [2]:
random_array = np.random.rand(3,5)
random_array

array([[0.33607845, 0.10650382, 0.84242795, 0.6404469 , 0.03677796],
       [0.87593094, 0.07499511, 0.23933773, 0.13780378, 0.48410398],
       [0.12885009, 0.85582407, 0.25762689, 0.12986733, 0.60141773]])

In [3]:
type(random_array)

numpy.ndarray

In [4]:
random_array.shape

(3, 5)

In [6]:
random_array.ndim

2

In [7]:
random_matrix = torch.rand(size = (3,5))
random_matrix

tensor([[0.9036, 0.2889, 0.5909, 0.6954, 0.1431],
        [0.2873, 0.9887, 0.7761, 0.1188, 0.6823],
        [0.6904, 0.9813, 0.5364, 0.4573, 0.9821]])

In [8]:
random_matrix.shape

torch.Size([3, 5])

In [9]:
random_matrix.ndim

2

Görsellerde genellikle 224, 224 ,3 boyutları kullanılır.

In [10]:
random_image_matrix = torch.rand(size = (224,224,3))
random_image_matrix

tensor([[[0.6776, 0.6016, 0.5396],
         [0.0382, 0.7284, 0.7577],
         [0.2084, 0.5185, 0.6215],
         ...,
         [0.6815, 0.8116, 0.8809],
         [0.3616, 0.9089, 0.2704],
         [0.8642, 0.3109, 0.8661]],

        [[0.1381, 0.3600, 0.0677],
         [0.4916, 0.9607, 0.9339],
         [0.6121, 0.2995, 0.6541],
         ...,
         [0.0094, 0.8445, 0.3010],
         [0.8904, 0.2517, 0.3639],
         [0.8537, 0.7260, 0.4405]],

        [[0.4199, 0.2829, 0.1941],
         [0.7213, 0.3954, 0.8464],
         [0.1466, 0.3774, 0.5551],
         ...,
         [0.9595, 0.1435, 0.5203],
         [0.6428, 0.1631, 0.5099],
         [0.9077, 0.2781, 0.4642]],

        ...,

        [[0.9936, 0.3433, 0.5283],
         [0.1711, 0.8322, 0.0187],
         [0.8738, 0.0560, 0.5515],
         ...,
         [0.5501, 0.4343, 0.1343],
         [0.7973, 0.4129, 0.4676],
         [0.7025, 0.5655, 0.9589]],

        [[0.7648, 0.2096, 0.3805],
         [0.7494, 0.5161, 0.8092],
         [0.

In [11]:
random_image_matrix.shape

torch.Size([224, 224, 3])

In [13]:
random_image_matrix.dim()

3

In [14]:
zeros = torch.zeros(size = (3,2))
zeros

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [15]:
ones = torch.ones(size = (3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [16]:
vector_with_arange = torch.arange(start = 0, end = 10, step = 1)
vector_with_arange

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
vector_with_arange = torch.arange(start = 0, end = 10, step = 2)
vector_with_arange

tensor([0, 2, 4, 6, 8])

In [18]:
similar_ones = torch.ones_like(input = vector_with_arange)
similar_ones

tensor([1, 1, 1, 1, 1])

In [19]:
tensor = torch.tensor([1,2,3])

In [20]:
tensor + 15

tensor([16, 17, 18])

In [21]:
tensor * 12

tensor([12, 24, 36])

In [22]:
tensor.subtract(3)

tensor([-2, -1,  0])

In [23]:
tensor.multiply(10)

tensor([10, 20, 30])

In [24]:
tensor * tensor

tensor([1, 4, 9])

In [25]:
tensor - tensor

tensor([0, 0, 0])

In [26]:
tensor2 = torch.tensor([4,5])

In [29]:
# tensor + tensor2

Bunu yaparsak boyut uyumsuzluğu uyarısı alacağız.

# Matris Çarpımı

In [30]:
tensor = torch.tensor([1,2,3])

In [31]:
tensor * tensor

tensor([1, 4, 9])

In [34]:
tensor = torch.tensor([[1,2,3],
                      [4,5,6],
                      [7,8,9]])

In [35]:
tensor * tensor

tensor([[ 1,  4,  9],
        [16, 25, 36],
        [49, 64, 81]])

In [36]:
tensor @ tensor

tensor([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])

In [37]:
torch.matmul(tensor, tensor)

tensor([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])

In [38]:
tensor1 = torch.tensor([[1,2],
                        [3,4],
                       [5,6]], dtype = torch.int32)

tensor2 = torch.tensor([[1,2],
                        [3,4],
                       [5,6]], dtype = torch.int32)

In [39]:
tensor1.shape, tensor2.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [40]:
# tensor1 @ tensor2

Bu işlemi yaptığımızda matris çarpımı için gerekli olan boyutlar sağlanmadığını ve boyut utuşmazlığı olduğunu alacağız.

In [41]:
tensor2.T

tensor([[1, 3, 5],
        [2, 4, 6]], dtype=torch.int32)

In [42]:
tensor1 @ tensor2.T

tensor([[ 5, 11, 17],
        [11, 25, 39],
        [17, 39, 61]], dtype=torch.int32)

In [44]:
tensor1.shape, tensor2.T.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [45]:
A = torch.tensor([[1.0, 2.0, 3.0]])

In [46]:
A.shape

torch.Size([1, 3])

In [47]:
A.ndim

2

In [48]:
B = torch.tensor([[4.0],
                  [5.0],
                  [6.0]])

In [49]:
B.shape

torch.Size([3, 1])

In [50]:
B.dim()

2

In [51]:
A @ B

tensor([[32.]])