In [1]:
import numpy as np
import torch

In [2]:
tensor = torch.arange(0,50,5)
tensor

tensor([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [3]:
tensor.min()

tensor(0)

In [4]:
tensor.max()

tensor(45)

In [5]:
tensor.sum()

tensor(225)

In [6]:
tensor.median()

tensor(20)

In [7]:
# tensor.mean()

Bu kod integer datatype olunca çalışmıyor.

In [8]:
tensor.dtype

torch.int64

In [9]:
tensor.type(torch.float)

tensor([ 0.,  5., 10., 15., 20., 25., 30., 35., 40., 45.])

In [10]:
tensor = tensor.type(torch.float)

In [11]:
tensor.mean()

tensor(22.5000)

In [12]:
tensor.max()

tensor(45.)

In [13]:
tensor.argmax()

tensor(9)

In [14]:
tensor[9]

tensor(45.)

In [15]:
matrix = torch.tensor([[1,2,3],[4,5,6]])

In [16]:
matrix[0]

tensor([1, 2, 3])

In [17]:
matrix[0][0]

tensor(1)