In [1]:
import numpy as np
import torch

In [2]:
tensor = torch.arange(0,50,5)
tensor

tensor([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [3]:
tensor.min()

tensor(0)

In [4]:
tensor.max()

tensor(45)

In [5]:
tensor.sum()

tensor(225)

In [6]:
tensor.median()

tensor(20)

In [7]:
# tensor.mean()

Bu kod integer datatype olunca çalışmıyor.

In [8]:
tensor.dtype

torch.int64

In [9]:
tensor.type(torch.float)

tensor([ 0.,  5., 10., 15., 20., 25., 30., 35., 40., 45.])

In [10]:
tensor = tensor.type(torch.float)

In [11]:
tensor.mean()

tensor(22.5000)

In [12]:
tensor.max()

tensor(45.)

In [13]:
tensor.argmax()

tensor(9)

In [14]:
tensor[9]

tensor(45.)

In [15]:
matrix = torch.tensor([[1,2,3],[4,5,6]])

In [16]:
matrix[0]

tensor([1, 2, 3])

In [17]:
matrix[0][0]

tensor(1)

In [18]:
x = torch.arange(
    start = 1,
    end = 10,
    step = 1
)

In [19]:
x

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
x.shape

torch.Size([9])

In [21]:
x_reshaped = x.reshape(1,9)

In [22]:
x_reshaped

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [23]:
x_reshaped.shape

torch.Size([1, 9])

In [24]:
x_reshaped = x_reshaped.reshape(3,3)

In [25]:
x_reshaped

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

### View

In [26]:
x_view = x.view(9,1)

In [27]:
x_view

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [28]:
x

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
x_reshaped

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [30]:
x_reshaped = x_reshaped.reshape(9,1)

In [31]:
x_reshaped

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [32]:
x_reshaped[0] = 20

In [33]:
x_reshaped

tensor([[20],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9]])

In [34]:
x

tensor([20,  2,  3,  4,  5,  6,  7,  8,  9])

x_reshaped'i değiştirince x'de değişti.

In [35]:
x_view[0] = 10

In [36]:
x_view

tensor([[10],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9]])

Peki farkları ne?

In [37]:
x = torch.tensor([[1,2,3],
                 [4,5,6]])

In [38]:
x.is_contiguous()

True

In [39]:
y = x.t()

In [40]:
y

tensor([[1, 4],
        [2, 5],
        [3, 6]])

In [41]:
y.is_contiguous()

False

In [42]:
x.view(1,6)

tensor([[1, 2, 3, 4, 5, 6]])

In [43]:
#y.view(1,6)

İşte fark burada ortaya çıkıyor. View sadece contigous tensorlerle kullanılabilir.

### Stacking

In [44]:
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [45]:
torch.stack(
    tensors = [x,x,x,x],
    dim = 0
)

tensor([[[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]]])

In [46]:
torch.stack(
    tensors = [x,x,x,x],
    dim = 1
)

tensor([[[1, 2, 3],
         [1, 2, 3],
         [1, 2, 3],
         [1, 2, 3]],

        [[4, 5, 6],
         [4, 5, 6],
         [4, 5, 6],
         [4, 5, 6]]])

### Squeeze and Unsqueeze

In [47]:
x.shape

torch.Size([2, 3])

In [48]:
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [49]:
x.squeeze()

tensor([[1, 2, 3],
        [4, 5, 6]])

In [50]:
y = x.unsqueeze(dim = 0)

In [51]:
y

tensor([[[1, 2, 3],
         [4, 5, 6]]])

In [52]:
y.shape

torch.Size([1, 2, 3])

In [53]:
z = y.unsqueeze(dim = 0)

In [54]:
z

tensor([[[[1, 2, 3],
          [4, 5, 6]]]])

In [55]:
z.shape

torch.Size([1, 1, 2, 3])

In [56]:
t = z.squeeze()

In [57]:
t

tensor([[1, 2, 3],
        [4, 5, 6]])

In [58]:
t.shape

torch.Size([2, 3])

### Permute

In [59]:
x = torch.rand(size = (224,224,3))

In [60]:
x.shape

torch.Size([224, 224, 3])

In [61]:
x_permuted = x.permute(2, 0, 1)

In [62]:
x_permuted.shape

torch.Size([3, 224, 224])

### Indexing and Slicing

In [63]:
a = torch.arange(1, 10, 1)

In [64]:
a

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
a = a.reshape(1, 3, 3)

In [66]:
a

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [67]:
a[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [68]:
a[0][0]

tensor([1, 2, 3])

In [69]:
a[0][0][0]

tensor(1)

In [70]:
a[:, 0]

tensor([[1, 2, 3]])

In [71]:
a[:, :, 1]

tensor([[2, 5, 8]])

In [72]:
a[:, 1, 1]

tensor([5])

### Random Seed

In [75]:
RANDOM_SEED = 10
torch.manual_seed(RANDOM_SEED)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.4581, 0.4829, 0.3125, 0.6150],
        [0.2139, 0.4118, 0.6938, 0.9693],
        [0.6178, 0.3304, 0.5479, 0.4440]])